sudo: true
language: haskell

ghc:
  - "8.2"

cache:
  directories:
    - "$HOME/.stack"


addons:
  apt:
    packages:
      - cabal-install-2.0


before_install:
  - mkdir -p ~/.local/bin
  - export PATH="$HOME/.local/bin:$PATH"
  - travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

install:

  - travis_wait 30 stack setup --no-terminal
  - stack ghc -- --version

  - travis_wait 40 stack build --only-dependencies --no-terminal
  - travis_wait 40 stack build --test --bench --haddock --no-run-tests --no-run-benchmarks --no-haddock-deps --no-terminal

script:

  - travis_wait 40 stack build --test --no-terminal

notifications:
  email: 
    on_failure: change
    on_success: change
